name: Release affected libraries

on: push

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'Build'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Setup
        uses: ./.github/actions/base_setup

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build_files
          path: dist

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: dist
