name: Test affected libraries

on: push

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: ./.github/actions/base_setup
      - name: Test
        run: |
          RUN=CI yarn run test-affected-libs

  # - name: Upload build
  #   uses: actions/upload-artifact@v3
  #   with:
  #     name: my-artifact
  #     path: dist

  # - name: Display structure of downloaded files
  #   run: ls -R
  #   working-directory: dist
